// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkKTba1bgBxXp9NHqGjmAO1Q8lpxwtBH0',
    appId: '1:335044278024:web:459c8691d2af51abee9ebd',
    messagingSenderId: '335044278024',
    projectId: 'quoteapp-123',
    authDomain: 'quoteapp-123.firebaseapp.com',
    storageBucket: 'quoteapp-123.firebasestorage.app',
    measurementId: 'G-6M2T3JG9ET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdPMlGWPH0eO7xaHKjs437ZLodEYmAQ9g',
    appId: '1:335044278024:android:9f2d1612895dcd33ee9ebd',
    messagingSenderId: '335044278024',
    projectId: 'quoteapp-123',
    storageBucket: 'quoteapp-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZxODnm8eOe8fEgp8aRcKvRezoxeq0FKU',
    appId: '1:335044278024:ios:4c63df6d6932cf49ee9ebd',
    messagingSenderId: '335044278024',
    projectId: 'quoteapp-123',
    storageBucket: 'quoteapp-123.firebasestorage.app',
    iosBundleId: 'com.example.quoteAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZxODnm8eOe8fEgp8aRcKvRezoxeq0FKU',
    appId: '1:335044278024:ios:4c63df6d6932cf49ee9ebd',
    messagingSenderId: '335044278024',
    projectId: 'quoteapp-123',
    storageBucket: 'quoteapp-123.firebasestorage.app',
    iosBundleId: 'com.example.quoteAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkKTba1bgBxXp9NHqGjmAO1Q8lpxwtBH0',
    appId: '1:335044278024:web:310d92eb5f0d36b8ee9ebd',
    messagingSenderId: '335044278024',
    projectId: 'quoteapp-123',
    authDomain: 'quoteapp-123.firebaseapp.com',
    storageBucket: 'quoteapp-123.firebasestorage.app',
    measurementId: 'G-CLDQ2W1GQ6',
  );
}
